---
title: "Generalized linear models - VT26 "
subtitle: "Inlämningsuppgift 1, 2.5 hp"
author: 
- David Müller
- Filip Ström
- Joel Söderman
date: last-modified
format: 
  pdf: default
  html:
    self-contained: true
language: 
  title-block-author-single: " "
crossref-fig-title: "Figur"
title-block-banner-color: Primary
title-block-published: "Publicerad"
author-title: "Gruppmedlemmar"
title-block-banner: true
editor: source
---

```{r}
#| output: false
#| echo: false
library('foreign')
library('haven') 
library('labelled')

load(url("https://raw.githubusercontent.com/johankoskinen/ST304G/main/data/GSS2022selection.RData"))

load(url("https://raw.githubusercontent.com/johankoskinen/ST304G/main/data/GSS2024selection.RData"))
```

```{r}
#| echo: false
table(GSSdata24$pres20, useNA='always')
table(GSSdata24$pres20==2, useNA='always')

my.small.model <- glm( pres20==2 ~ I(sex==2)+ I(owngun==1), data = GSSdata24, family = "binomial")
summary(my.small.model)
```

# Task 1
```{r}
table(GSSdata24$pres20, useNA='always')
table(GSSdata24$pres20==2, useNA='always')

model_24 <- glm( pres20==2 ~ 
                   I(sex==2) + 
                   I(owngun==1) +
                   I(degree %in% c(4,5)), 
                 data = GSSdata24,
                 family = "binomial")

summary(model_24)

model_22 <- glm((pres20 == 2) ~ 
                  I(sex == 2) + 
                  I(owngun == 1) + 
                  I(degree %in% c(4,5)),
               family = "binomial",
               data = GSSdata22)

summary(model_22)
```
CHATGPT-KOD
```{r}
common <- intersect(names(GSSdata22), names(GSSdata24))

GSSdata22_sub <- GSSdata22[, common]
GSSdata24_sub <- GSSdata24[, common]

GSSdata22_sub$year <- 2022
GSSdata24_sub$year <- 2024

GSSdata <- rbind(GSSdata22_sub, GSSdata24_sub)
```

```{r}
GSSdata$year2024 <- ifelse(GSSdata$year == 2024, 1, 0)

model <- glm(pres20 == 2 ~ 
               I(sex == 2) * year2024 + 
               I(owngun == 1) +
               I(degree %in% c(4,5)),
             data = GSSdata,
             family = binomial)

summary(model)
```
$$z_{\text{obs}} = \frac{\hat{\beta}_{\text{sex,22}} - \hat{\beta}_{\text{sex,24}}}{\sqrt{\mathrm{SE}(\hat{\beta}_{\text{sex,22}})^2 + \mathrm{SE}(\hat{\beta}_{\text{sex,24}})^2}}$$

# Task 2:
```{r}
# Välj alla variabler som används i någon av modellerna
vars_needed <- c(
  "pres20", "sex", "owngun", "degree",
  "region", "race", "res16", "realinc"
)

# Behåll bara kompletta observationer
GSS_clean <- na.omit(GSSdata24[, vars_needed])

# Small logit
m_small_logit <- glm(
  pres20 == 2 ~
    I(sex == 2) +
    I(owngun == 1) +
    I(degree %in% c(4, 5)),
  data = GSS_clean,
  family = binomial(link = "logit")
)

# Big logit
m_big_logit <- glm(
  pres20 == 2 ~
    I(sex == 2) +
    I(owngun == 1) +
    I(degree %in% c(4, 5)) +
    factor(region) +
    factor(race) +
    factor(res16) +
    log(realinc),
  data = GSS_clean,
  family = binomial(link = "logit")
)

# Small probit
m_small_probit <- glm(
  pres20 == 2 ~
    I(sex == 2) +
    I(owngun == 1) +
    I(degree %in% c(4, 5)),
  data = GSS_clean,
  family = binomial(link = "probit")
)

# Big probit
m_big_probit <- glm(
  pres20 == 2 ~
    I(sex == 2) +
    I(owngun == 1) +
    I(degree %in% c(4, 5)) +
    factor(region) +
    factor(race) +
    factor(res16) +
    log(realinc),
  data = GSS_clean,
  family = binomial(link = "probit")
)

# Sammanfattningar
summary(m_small_logit)
summary(m_big_logit)
summary(m_small_probit)
summary(m_big_probit)

# Modelljämförelser
anova(m_small_logit, m_big_logit, test = "Chisq")
anova(m_small_probit, m_big_probit, test = "Chisq")

# AIC-jämförelse
AIC(m_small_logit, m_big_logit, m_small_probit, m_big_probit)

# Kontroll: alla modeller ska nu ha samma antal observationer
nobs(m_small_logit)
nobs(m_big_logit)
nobs(m_small_probit)
nobs(m_big_probit)

```

# Task 3

MIDWEST = 2
data = GSSdata24
```{r}
predict(*vilken modell*, 
        newdata = *newdata som innehåller region == 2*,
        type = "response")
```
```{r}
#| fig-width: 5
#| fig-height: 3
#| out-width: "50%"
#| layout-ncol: 2
#| fig-align: center
#| echo: false
```







